//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Mon Mar 03 04:37:53 EST 2003
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class A5Sym {
  /* terminals */
  public static final int MULTI = 4;
  public static final int READ = 23;
  public static final int ELSE = 21;
  public static final int PLUS = 2;
  public static final int NOTEQ = 11;
  public static final int RPAREN = 7;
  public static final int INT = 15;
  public static final int SEMI = 14;
  public static final int RETURN = 19;
  public static final int END = 13;
  public static final int TRUE = 26;
  public static final int IF = 20;
  public static final int LPAREN = 6;
  public static final int WRITE = 22;
  public static final int ID = 8;
  public static final int BEGIN = 12;
  public static final int STRING = 17;
  public static final int COMMA = 9;
  public static final int NUMBER = 28;
  public static final int EOF = 0;
  public static final int DIVIDE = 5;
  public static final int MAIN = 25;
  public static final int FALSE = 27;
  public static final int MINUS = 3;
  public static final int error = 1;
  public static final int Qstring = 24;
  public static final int ASSIGN = 18;
  public static final int EQUAL = 10;
  public static final int REAL = 16;

}